services:
#    catalog.example:
#        class: CatalogBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    user_provider:
        class: CatalogBundle\Entity\UserProvider