<?php
namespace CatalogBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
    public function getAllByIdNameLvl()
    {
        return $this->_em->createQueryBuilder()
            ->select('n.id, n.title, n.lvl')
            ->from('CatalogBundle:Category', 'n')
            ->getQuery()
            ->getResult();
    }
}
