<?php
namespace CatalogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CatalogBundle\Entity\Category;
use Symfony\Component\Form\Form;
use CatalogBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getByPage($page, $per_page, $ordered_by, $direction)
    {
        $directionDQL = 'ASC';
        if ($direction) {
            $directionDQL = 'ASC';
        } else {
            $directionDQL = 'DESC';
        }

        $products = $this->_em
            ->createQueryBuilder()
            ->select('p')
            ->from('CatalogBundle:Product', 'p')
            ->orderBy('p.' . $ordered_by, $directionDQL)
            ->setFirstResult(($page-1)*$per_page)
            ->setMaxResults($per_page)
            ->getQuery()
            ->getResult();

        return $products;
    }

    public function getByCategory($category_id)
    {

        $products = $this->_em
            ->createQueryBuilder()
            ->select('p')
            ->from('CatalogBundle:Product', 'p')
            ->where('p.category=' . $category_id)
            ->getQuery();

        return $products;
    }

    public function insertDataFromForm(Form $form)
    {
        /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
        $file = $form->get('image')->getData();
        $fileName = md5(uniqid()).'.'.$file->guessExtension();

        $file->move(
            'uploads/images',
            $fileName
        );

        $now = new\DateTime('now');
        $first_good = new Product();
        $first_good->setName($form->get('name')->getData());
        $first_good->setStateFlag(true);
        $first_good->setCategory(
            $this->_em
                ->getRepository('CatalogBundle:Category')
                ->findOneById($form->get('category')->getData())
        );

        $first_good->setDescription($form->get('description')->getData());
        $first_good->setSku($form->get('sku')->getData());
        $first_good->setCreationTime($now);
        $first_good->setLastModification($now);
        $first_good->setImage($fileName);
        $this->_em->persist($first_good);
        $this->_em->flush();
    }
}