# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.product_api_service:
        class: CatalogBundle\Service\ProductAPIService

    app.form.type.category:
        class: CatalogBundle\Form\Type\CategoryType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }